/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4-dev at Thu Aug 13 18:03:25 2015. */

#ifndef PB_STATUS_PB_H_INCLUDED
#define PB_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _status {
    bool has_system_temp;
    int32_t system_temp;
    bool has_bv;
    float bv;
    bool has_pv;
    float pv;
    bool has_cpu_load;
    int32_t cpu_load;
    bool has_gps_health;
    int32_t gps_health;
    bool has_hx1_health;
    int32_t hx1_health;
    bool has_rockblock_health;
    int32_t rockblock_health;
    bool has_watchdog_last_fired;
    int32_t watchdog_last_fired;
} status;

/* Default values for struct fields */

/* Initializer values for message structs */
#define status_init_default                      {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define status_init_zero                         {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define status_system_temp_tag                   1
#define status_bv_tag                            2
#define status_pv_tag                            3
#define status_cpu_load_tag                      4
#define status_gps_health_tag                    5
#define status_hx1_health_tag                    6
#define status_rockblock_health_tag              7
#define status_watchdog_last_fired_tag           8

/* Struct field encoding specification for nanopb */
extern const pb_field_t status_fields[9];

/* Maximum encoded size of messages (where known) */
#define status_size                              76

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define STATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
