/*
 * This file was generated by linkcmd_gnu.xdt from the ti.platforms.msp432 package.
 */

__STACK_SIZE = 0x300;
__TI_STACK_SIZE = __STACK_SIZE;

INPUT(
    /home/vagrant/workspace_v6_1/Octanis1-Mainboard-Firmware_MSP_EXP432P401RLP/Debug/configPkg/package/cfg/app_pm4fg.om4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/uia_2_00_02_39/packages/ti/uia/sysbios/lib/release/ti.uia.sysbios.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/uia_2_00_02_39/packages/ti/uia/loggers/lib/release/ti.uia.loggers.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/packages/ti/drivers/lib/drivers_MSP432P401R_instrumented.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/packages/ti/drivers/ports/tirtos/lib/tirtosport.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/bios_6_41_03_51/packages/ti/sysbios/fatfs/lib/release/ti.sysbios.fatfs.am4fg
    /home/vagrant/workspace_v6_1/Octanis1-Mainboard-Firmware_MSP_EXP432P401RLP/src/sysbios/sysbios.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/uia_2_00_02_39/packages/ti/uia/services/lib/release/ti.uia.services.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/uia_2_00_02_39/packages/ti/uia/runtime/lib/release/ti.uia.runtime.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/uia_2_00_02_39/packages/ti/uia/events/lib/release/ti.uia.events.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/bios_6_41_03_51/packages/gnu/targets/arm/rtsv7M/lib/gnu.targets.arm.rtsv7M.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/bios_6_41_03_51/packages/gnu/targets/arm/rtsv7M/lib/boot.am4fg
    /home/vagrant/ti/tirtos_msp43x_2_12_00_24/products/bios_6_41_03_51/packages/gnu/targets/arm/rtsv7M/lib/syscalls.am4fg
)

/*
 * symbolic aliases for static instance objects
 */
xdc_runtime_Startup__EXECFXN__C = 1;
xdc_runtime_Startup__RESETFXN__C = 1;
TSK_idle = ti_sysbios_knl_Task_Object__table__V + 76;


SECTIONS {

        .bootVecs (DSECT) : {*(.bootVecs)} 
    xdc.meta (COPY) : {KEEP(*(xdc.meta))}  AT> REGION_TEXT


    /*
     * Linker command file contributions from all loaded packages:
     */
    
/* Content from ti.sysbios.family.arm (ti/sysbios/family/arm/linkcmd.xdt): */

/* Content from ti.sysbios.rts (ti/sysbios/rts/linkcmd.xdt): */

/* Content from ti.sysbios.family.arm.m3 (ti/sysbios/family/arm/m3/linkcmd.xdt): */
    _intvecs_base_address = 0;
    _vtable_base_address = 536870912;
ti_sysbios_family_arm_m3_Hwi_nvic = 0xe000e000;


    __TI_STACK_BASE = __stack;
}

ENTRY(_c_int00)

/* function aliases */
xdc_runtime_System_asprintf_va__E = xdc_runtime_System_asprintf_va__F;
xdc_runtime_System_snprintf_va__E = xdc_runtime_System_snprintf_va__F;
xdc_runtime_System_printf_va__E = xdc_runtime_System_printf_va__F;
xdc_runtime_System_aprintf_va__E = xdc_runtime_System_aprintf_va__F;
xdc_runtime_System_sprintf_va__E = xdc_runtime_System_sprintf_va__F;

